[package]
name = "wolfgang_alpha"
version = "0.1.0"
authors = ["LvnRtg <ortega@lieven.fr>"]
edition = "2024"

[dependencies]
# getrandom is needed by wasm/dioxus for whatever reason
getrandom = { version = "0.2.17", features = ["js"] }
dioxus = { version = "0.7.9", features = [] }
wasm-bindgen-futures = "0.4.77"
tracing-wasm = "0.2.1"
web-sys = { version = "0.3.91", features = [
    "Window",
    "Navigator",
    "Clipboard"
]}
statrs = "0.18.0"
itertools = "0.14.0"
num-traits = "0.2.19"
rayon = "1"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
